"""Исправление отношения между ReferralCode и Referral

Revision ID: 01995e917be4
Revises: 1869f66289fb
Create Date: 2024-10-27 22:18:49.526615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01995e917be4'
down_revision: Union[str, None] = '1869f66289fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'referrals', 'referralcodes', ['referral_code_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    # ### end Alembic commands ###
