"""create referrals_code_id nullabale True

Revision ID: 61dc396c3216
Revises: 65bcd4569aa9
Create Date: 2024-10-28 13:49:01.542666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61dc396c3216'
down_revision: Union[str, None] = '65bcd4569aa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('referrals', 'referral_code_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('referrals', 'referral_code_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
