"""Add referral_id to users

Revision ID: 7c117d5316c2
Revises: 01995e917be4
Create Date: 2024-10-28 10:16:40.124488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c117d5316c2'
down_revision: Union[str, None] = '01995e917be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referral_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'referrals', ['referral_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'referral_id')
    # ### end Alembic commands ###
